#!/usr/bin/env python3

tpl = '''# THIS FILE IS AUTOGENERATED -- DO NOT EDIT #
#   Edit and Re-run .ci/gitlab/template.ci.py instead       #

stages:
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"

#************ definition of base jobs *********************************************************************************#

.per_py:
    retry:
        max: 2
        when:
            - runner_system_failure
            - stuck_or_timeout_failure
            - api_failure

    tags:
      - long execution time
      - docker-in-docker
    script:
      - make ${TARGET}_${PYVER}
      - make push_${TARGET}_${PYVER}
    before_script:
      - apk --update add openssh-client rsync git file make bash
      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
    image: docker:stable
    services:
        - docker:dind

.py_indep:
    extends: .per_py
    script:
      - make ${TARGET}
      - make push_${TARGET}

#******* stage 1

ci_sanity:
  extends: .py_indep
  stage: "1"
  variables:
      PYVER: "{{PY}}"
      TARGET: ci_sanity

{%- for PY in pythons %}
python {{PY}}:
    extends: .per_py
    stage: "1"
    variables:
        PYVER: "{{PY}}"
        TARGET: python
{% endfor %}

#******* stage 2
{%- for PY in pythons %}
constraints {{PY}}:
    extends: .per_py
    stage: "2"
    variables:
        PYVER: "{{PY}}"
        TARGET: constraints
{% endfor %}

{%- for PY in pythons %}
dealii {{PY}}:
    extends: .per_py
    stage: "2"
    variables:
        PYVER: "{{PY}}"
        TARGET: dealii
{% endfor %}



{%- for PY in pythons %}
petsc {{PY}}:
    extends: .per_py
    stage: "2"
    variables:
        PYVER: "{{PY}}"
        TARGET: petsc
{% endfor %}

#******* stage 3
{%- for PY in pythons %}
pypi-mirror_stable {{PY}}:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "{{PY}}"
        TARGET: pypi-mirror_stable
{% endfor %}

{%- for PY in pythons %}
pypi-mirror_oldest {{PY}}:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "{{PY}}"
        TARGET: pypi-mirror_oldest
{% endfor %}

{%- for PY in pythons %}
ngsolve {{PY}}:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "{{PY}}"
        TARGET: ngsolve
{% endfor %}


{%- for PY in pythons %}
fenics {{PY}}:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "{{PY}}"
        TARGET: fenics
{% endfor %}

#******* stage 4

{%- for PY in pythons %}
{%- for ml in manylinux %}
wheelbuilder_manylinux{{ml}} {{PY}}:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "{{PY}}"
        TARGET: wheelbuilder_manylinux{{ml}}
{% endfor %}
{% endfor %}

{%- for PY in pythons %}
cibase {{PY}}:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "{{PY}}"
        TARGET: cibase
{% endfor %}


#******* stage 5

{%- for PY in pythons %}
testing {{PY}}:
    extends: .per_py
    stage: "5"
    variables:
        PYVER: "{{PY}}"
        TARGET: testing
{% endfor %}

demo_master:
  extends: .py_indep
  stage: "5"
  variables:
      PYVER: "{{PY}}"
      TARGET: demo_master


#******* stage 6

{%- for PY in pythons %}
jupyter {{PY}}:
    extends: .per_py
    stage: "6"
    variables:
        PYVER: "{{PY}}"
        TARGET: jupyter
{% endfor %}

docker-in-docker:
  extends: .py_indep
  stage: "6"
  variables:
      PYVER: "{{PY}}"
      TARGET: docker-in-docker

# THIS FILE IS AUTOGENERATED -- DO NOT EDIT #
#   Edit and Re-run .ci/gitlab/template.ci.py instead       #

'''


import os
import jinja2
import sys
from itertools import product
from pathlib import Path

tpl = jinja2.Template(tpl)
pythons = ['3.6', '3.7', '3.8']
manylinux = ['1', '2010', '2014']

with open(os.path.join(os.path.dirname(__file__), '.gitlab-ci.yml'), 'wt') as yml:
    yml.write(tpl.render(**locals()))
