

stages:
  - static_targets
  - parameterized_targets

#************ definition of base jobs *********************************************************************************#
# https://docs.gitlab.com/ee/ci/yaml/README.html#workflowrules-templates
include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

.docker_base:
    retry:
        max: 2
        when:
            - runner_system_failure
            - stuck_or_timeout_failure
            - api_failure

    tags:
      - amm-only_sb_dind
    variables:
      DOCKER_CLI_EXPERIMENTAL: enabled
    before_script:
      - docker buildx --help
      - apk add make sed rsync bash git
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD docker.io
parameterized_targets 3 6:
    extends: .docker_base
    resource_group: cache_3.6
    stage: parameterized_targets
    variables:
        PYVER: "3.6"
    script:
      - make python_builder_3.6
      # wait for potentially running push
      - wait
      - make push_python_builder_3.6 &

      - make python_3.6
      # wait for potentially running push
      - wait
      - make push_python_3.6 &

      - make constraints_3.6
      # wait for potentially running push
      - wait
      - make push_constraints_3.6 &

      - make dealii_3.6
      # wait for potentially running push
      - wait
      - make push_dealii_3.6 &

      - make petsc_3.6
      # wait for potentially running push
      - wait
      - make push_petsc_3.6 &

      - make pypi-mirror_stable_3.6
      # wait for potentially running push
      - wait
      - make push_pypi-mirror_stable_3.6 &

      - make pypi-mirror_oldest_3.6
      # wait for potentially running push
      - wait
      - make push_pypi-mirror_oldest_3.6 &

      - make ngsolve_3.6
      # wait for potentially running push
      - wait
      - make push_ngsolve_3.6 &

      - make fenics_3.6
      # wait for potentially running push
      - wait
      - make push_fenics_3.6 &

      - make wheelbuilder_manylinux2010_3.6
      # wait for potentially running push
      - wait
      - make push_wheelbuilder_manylinux2010_3.6 &

      - make wheelbuilder_manylinux2014_3.6
      # wait for potentially running push
      - wait
      - make push_wheelbuilder_manylinux2014_3.6 &

      - make cibase_3.6
      # wait for potentially running push
      - wait
      - make push_cibase_3.6 &

      - make testing_3.6
      # wait for potentially running push
      - wait
      - make push_testing_3.6 &

      - make jupyter_3.6
      # wait for potentially running push
      - wait
      - make push_jupyter_3.6 &

      - wait

parameterized_targets 3 7:
    extends: .docker_base
    resource_group: cache_3.7
    stage: parameterized_targets
    variables:
        PYVER: "3.7"
    script:
      - make python_builder_3.7
      # wait for potentially running push
      - wait
      - make push_python_builder_3.7 &

      - make python_3.7
      # wait for potentially running push
      - wait
      - make push_python_3.7 &

      - make constraints_3.7
      # wait for potentially running push
      - wait
      - make push_constraints_3.7 &

      - make dealii_3.7
      # wait for potentially running push
      - wait
      - make push_dealii_3.7 &

      - make petsc_3.7
      # wait for potentially running push
      - wait
      - make push_petsc_3.7 &

      - make pypi-mirror_stable_3.7
      # wait for potentially running push
      - wait
      - make push_pypi-mirror_stable_3.7 &

      - make pypi-mirror_oldest_3.7
      # wait for potentially running push
      - wait
      - make push_pypi-mirror_oldest_3.7 &

      - make ngsolve_3.7
      # wait for potentially running push
      - wait
      - make push_ngsolve_3.7 &

      - make fenics_3.7
      # wait for potentially running push
      - wait
      - make push_fenics_3.7 &

      - make wheelbuilder_manylinux2010_3.7
      # wait for potentially running push
      - wait
      - make push_wheelbuilder_manylinux2010_3.7 &

      - make wheelbuilder_manylinux2014_3.7
      # wait for potentially running push
      - wait
      - make push_wheelbuilder_manylinux2014_3.7 &

      - make cibase_3.7
      # wait for potentially running push
      - wait
      - make push_cibase_3.7 &

      - make testing_3.7
      # wait for potentially running push
      - wait
      - make push_testing_3.7 &

      - make jupyter_3.7
      # wait for potentially running push
      - wait
      - make push_jupyter_3.7 &

      - wait

parameterized_targets 3 8:
    extends: .docker_base
    resource_group: cache_3.8
    stage: parameterized_targets
    variables:
        PYVER: "3.8"
    script:
      - make python_builder_3.8
      # wait for potentially running push
      - wait
      - make push_python_builder_3.8 &

      - make python_3.8
      # wait for potentially running push
      - wait
      - make push_python_3.8 &

      - make constraints_3.8
      # wait for potentially running push
      - wait
      - make push_constraints_3.8 &

      - make dealii_3.8
      # wait for potentially running push
      - wait
      - make push_dealii_3.8 &

      - make petsc_3.8
      # wait for potentially running push
      - wait
      - make push_petsc_3.8 &

      - make pypi-mirror_stable_3.8
      # wait for potentially running push
      - wait
      - make push_pypi-mirror_stable_3.8 &

      - make pypi-mirror_oldest_3.8
      # wait for potentially running push
      - wait
      - make push_pypi-mirror_oldest_3.8 &

      - make ngsolve_3.8
      # wait for potentially running push
      - wait
      - make push_ngsolve_3.8 &

      - make fenics_3.8
      # wait for potentially running push
      - wait
      - make push_fenics_3.8 &

      - make wheelbuilder_manylinux2010_3.8
      # wait for potentially running push
      - wait
      - make push_wheelbuilder_manylinux2010_3.8 &

      - make wheelbuilder_manylinux2014_3.8
      # wait for potentially running push
      - wait
      - make push_wheelbuilder_manylinux2014_3.8 &

      - make cibase_3.8
      # wait for potentially running push
      - wait
      - make push_cibase_3.8 &

      - make testing_3.8
      # wait for potentially running push
      - wait
      - make push_testing_3.8 &

      - make jupyter_3.8
      # wait for potentially running push
      - wait
      - make push_jupyter_3.8 &

      - wait

parameterized_targets 3 9:
    extends: .docker_base
    resource_group: cache_3.9
    stage: parameterized_targets
    variables:
        PYVER: "3.9"
    script:
      - make python_builder_3.9
      # wait for potentially running push
      - wait
      - make push_python_builder_3.9 &

      - make python_3.9
      # wait for potentially running push
      - wait
      - make push_python_3.9 &

      - make constraints_3.9
      # wait for potentially running push
      - wait
      - make push_constraints_3.9 &

      - make dealii_3.9
      # wait for potentially running push
      - wait
      - make push_dealii_3.9 &

      - make petsc_3.9
      # wait for potentially running push
      - wait
      - make push_petsc_3.9 &

      - make pypi-mirror_stable_3.9
      # wait for potentially running push
      - wait
      - make push_pypi-mirror_stable_3.9 &

      - make pypi-mirror_oldest_3.9
      # wait for potentially running push
      - wait
      - make push_pypi-mirror_oldest_3.9 &

      - make ngsolve_3.9
      # wait for potentially running push
      - wait
      - make push_ngsolve_3.9 &

      - make fenics_3.9
      # wait for potentially running push
      - wait
      - make push_fenics_3.9 &

      - make wheelbuilder_manylinux2010_3.9
      # wait for potentially running push
      - wait
      - make push_wheelbuilder_manylinux2010_3.9 &

      - make wheelbuilder_manylinux2014_3.9
      # wait for potentially running push
      - wait
      - make push_wheelbuilder_manylinux2014_3.9 &

      - make cibase_3.9
      # wait for potentially running push
      - wait
      - make push_cibase_3.9 &

      - make testing_3.9
      # wait for potentially running push
      - wait
      - make push_testing_3.9 &

      - make jupyter_3.9
      # wait for potentially running push
      - wait
      - make push_jupyter_3.9 &

      - wait
static_targets:
    extends: .docker_base
    resource_group: cache_
    stage: static_targets
    variables:
        PYVER: ""
    script:
      - make docker-in-docker
      - wait
      - make push_docker-in-docker &

      - make docs
      - wait
      - make push_docs &

      - make demo_main
      - wait
      - make push_demo_main &

      - make deploy_checks
      - wait
      - make push_deploy_checks &

      - make ci_sanity
      - wait
      - make push_ci_sanity &

      - wait


# THIS FILE IS AUTOGENERATED -- DO NOT EDIT #
#   Edit and Re-run template.ci.py instead       #
