# EXPERIMENTAL_SYNTAX
FROM REGISTRY/pymor/jupyter_pyPYVER:VERTAG

MAINTAINER René Fritze <rene.fritze@wwu.de>

RUN useradd -m -g 100 -u 1000 jovyan
USER jovyan

ENV HOME=/home/jovyan
VOLUME /home/jovyan
WORKDIR /home/jovyan

ENTRYPOINT []
